### ISSUE TITLE
Test suite disables too much

### ISSUE THREAD

**Issue by danielshahaf** [sailfishos-chum/zsh-packaging#1]
https://github.com/sailfishos-chum/zsh-packaging/blob/a3e3d1716f836633e9b7b4c849aa5dd9af3c26ca/rpm/zsh.spec#L66-L75

That disables [the entire D02glob.ztst file](https://github.com/zsh-users/zsh/blob/zsh-5.8.1/Test/D02glob.ztst), even though the quoted error message is specific to a particular test point.

Instead of disabling the entire file, which comprises ~60 test points, only the one or two test points that "expected to fail, but passed" should be disabled (or better yet, have their "expected to fail" annotations removed).

**Comment by takimata** [comment]
Or rather, fix the root cause instead of disabling tests :-)

But of course, the second best alternative would be to only disable the specific tests. As I have more pressing things to do than investigating the cause for this behaviour, patches are welcome :-) Also, I don't know whether this issue still persists with Vanha Rauma 4.4.0...

I guess zsh works fine for you apart from this issue?

**Comment by danielshahaf** [comment]
> I guess zsh works fine for you apart from this issue?

I don't run Sailfish anywhere.

As to a patch: there's only one expected-to-fail test in D02 (`Test/list-XFails | grep D02` prints only `Test/D02glob.ztst:773:-f:(workers/45367) modifier ':P' squashes multiple slashes`).  I think the easiest patch would be this:

```diff
--- a/Test/D02glob.ztst
+++ b/Test/D02glob.ztst
@@ -770,6 +770,7 @@
 >glob.tmp/not-a-directory ,
 
  () { echo $1:P } ////dev
+ ZTST_skip="skip because it passes on OBS on aarch64"
 -f:(workers/45367) modifier ':P' squashes multiple slashes
 >/dev  
 
```

This would make the test run but not without checking the exit code / stdout / stderr.

Alternatively, you might consider changing `-f:` to `0:`, which would mark the test as expected-to-pass.  Judging by the comments in the spec file, you'll want to only make this change on some archs but not on others; however, I don't know how to write the condition for that in your environment.

**Comment by danielshahaf** [comment]
> I think the easiest patch would be this:

To be precise: this, and removing the special-case handling of D02glob.ztst from the spec file.

**Comment by takimata** [comment]
Thanks for the hints. I didn't know that you're a zsh contributor.

With zsh 5.8.1, there is actually another test (which was/is the culprit):

    $ Test/list-XFails | grep D02
    Test/D02glob.ztst:744:-f:unreadable directories can be globbed (users/24619, users/24626)
    Test/D02glob.ztst:753:-f:(workers/45367) modifier ':P' squashes multiple slashes
